language: csharp
mono: none
dotnet: 2.1.805
script:
- dotnet restore
deploy:
  provider: script
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master"
  script: "./deploy.sh"
branches:
  only:
  - master
  - "/^release.*/"
env:
  global:
  - secure: 6taVfBaGrpQH9vsmTTNmaiQttsXKJiR+txwZkr+gi8uI6LwG6AEiLnpLIRoTYKjUGORPYZjaXkV3LyNMA68L1XY4rCBDH/ci88iFP8kWQtOPqJCTHBXcivOlEEC2v0D2XJVlc9EeIVBrv0nVQ/W0NUTV8lkrmDTBEN398e4NfqIH4/cYxqCk+eRYCL6+ahmetRDDuspg+GrGOdlbmLBxE/asprpS3/rRl2aMBEx2Us90BtbAfDfYIZJzj2b8LxF/MGcaVRZqF1Qc3Nba6PNYAjDdT724oW8jkbcLMnMDPj8J/pLD29QB+bg7oSgowh81ymOLkc6ppvIcVZsnzCe58FlqhULobk5bPSZqHk8Hg8PhTrFcgdzh8ylJ6HPl1XgulN4aPsHy4HX9aDxQPfqedsSCXoGaFO0+bdtqMkpakW+5Xq283qssN0l1cAkNUTtDSj/9Lp0BmaaP9PuEbT+z+CThu1Je2//XOoibNsJGcAi2Q7kaAuZeUWh/QW0S/Fs9qbdDYkh2roO3JV6sOEUa1zbqTBofLDPq3curzf6FpVlDB0ZdxgYPOgB7lsZad9sYGOM9n7oPZc7vPfXElGQneQI3cri9EGpUzxsVlndLiRkIlCQVm0CbS+AJ7YNtMl4+ZgepcnUcwzwyDJG7e003L/A8687G0NsAi+C3e0WPgWg=
  - secure: BeC1HM5GVxYx0jkY+P6/kwx4TD5DPibZK7gJ0Gx8kfluwxxU/Pbq2sM4Ecttk+/WfgjEYSvjQj/R2dLbrYuC1BU0x/XcHD08jEYLeETIGMcMcBPeuUAVfjcYbAnLX60RbToD2VL4WRTHrY7r6pNiXLcYic6v7Eutd/ibFfdLMuTRceVp5B9sTA/XNMjmObLHtf5o4E7RhTbo0OoX2sKg2U56On9cTdCiWrwhrbQCgca4pMpYEyEToHl06KBo8ZXUEErvkc2Kqc+ykS/68ylkRVPD2tM636v6lQwSyLKPtcNjBdRGmKNGxq3e6UtqT2y+jgmNq5c/STE/gAPGGgYyRsbkvDvMVG5OE038T1UDl8p+9Fc1W0AJxXWlVhACY8tYhMu7FLdeQ2Xnwnv/4k24Wds8bGkz3rjArSKiAZQ8SCbGQGM3yDy+7iwmLaf6xsp60020MaOJm6+MoNocE9oC8H8mdkxc/ukdIctqpQTPWr96u5mehSKwr5f8n0fdtt/656VD/qgQepC9867rcApH7adN6j8KqGuCVK0sci23REWR6QRCKZ5RT9SOmWFfN5wyY27ELubRW1cYf0sL88h+1DVS5ZTO9pOonXrv1jNhisYs4+L2NBbpYDHXhfmv+UIMCa1YSBfA5HVnrwiYJteW2/zq5NBJswaaLCVIY08AJwI=
